# Generated by Django 5.2.12 on 2026-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partnerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrequest',
            name='message',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='partnerrequest',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
