# Generated by Django 5.2.12 on 2026-03-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
